# frozen_string_literal: true
source "https://rubygems.org"

gem "mysql2"
gem 'sinatra'
gem 'activerecord'
gem 'hashie'
gem "sinatra-activerecord"
gem "rspec"
gem "factory_girl"

group :test do
  gem 'rspec'
end

